# Generated by Django 2.2.4 on 2019-10-01 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_time',
            new_name='pub_date',
        ),
    ]
